// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2FwOTsns4ruP1mnlr8gKuZl04eqFsK4',
    appId: '1:167133589536:web:17e9e0a6b5df193d5d4c45',
    messagingSenderId: '167133589536',
    projectId: 'ensemble-3ccfc',
    authDomain: 'ensemble-3ccfc.firebaseapp.com',
    storageBucket: 'ensemble-3ccfc.firebasestorage.app',
    measurementId: 'G-9STXVWW560',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2INVyHdg2_QNticQUAgy-hCjilqOUllc',
    appId: '1:167133589536:android:1469f0a51056f8fc5d4c45',
    messagingSenderId: '167133589536',
    projectId: 'ensemble-3ccfc',
    storageBucket: 'ensemble-3ccfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUAb5cjwhVEj0wZtoxPBe9ldk5_quNhKg',
    appId: '1:167133589536:ios:f8d6bdbaa6ab75195d4c45',
    messagingSenderId: '167133589536',
    projectId: 'ensemble-3ccfc',
    storageBucket: 'ensemble-3ccfc.firebasestorage.app',
    iosBundleId: 'com.example.bypass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUAb5cjwhVEj0wZtoxPBe9ldk5_quNhKg',
    appId: '1:167133589536:ios:f8d6bdbaa6ab75195d4c45',
    messagingSenderId: '167133589536',
    projectId: 'ensemble-3ccfc',
    storageBucket: 'ensemble-3ccfc.firebasestorage.app',
    iosBundleId: 'com.example.bypass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8e0nbfEtyWllGFl5ZJPeJb1l_biZt7pY',
    appId: '1:167133589536:web:10451c7f62571fc85d4c45',
    messagingSenderId: '167133589536',
    projectId: 'ensemble-3ccfc',
    authDomain: 'ensemble-3ccfc.firebaseapp.com',
    storageBucket: 'ensemble-3ccfc.firebasestorage.app',
    measurementId: 'G-N6G3150EYR',
  );

}